### ISSUE TITLE
Crash on startup on server caused by the AoA particle patch

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#104]
[crash-2023-09-06_13.43.20-server.txt](https://github.com/embeddedt/ArchaicFix/files/12536964/crash-2023-09-06_13.43.20-server.txt)

**Comment by embeddedt** [comment]
Note to self: mark the mixin as client-only.

**Comment by embeddedt** [comment]
Fixed in 0.6.2.
