### ISSUE TITLE
Falling items very slow

### ISSUE THREAD

**Issue by Pilzinsel64** [embeddedt/ArchaicFix#114]
See the video. I don't see any relevant configuration, so I assume that's a side-effect from something or a bug.

https://cloud.pilzinsel64.de/s/CKxWBo9YQ6b63Zo

**Comment by Pilzinsel64** [comment]
Ah, I see that behavior comes from `itemLagReduction`. I truned it off and now it works like before.

Is that intended behavior for this or a bug?

**Comment by makamys** [comment]
Sounds related to https://github.com/embeddedt/ArchaicFix/issues/38 which happened with Ships Mod.

**Comment by Pilzinsel64** [comment]
Hm, don't have the ships mod. Maybe there is another one. 🤔

**Comment by jss2a98aj** [comment]
This is most likely an interaction with Et Futurum Requiem's feature that makes some dropped items float on lava.

**Comment by Pilzinsel64** [comment]
> interaction with Et Futurum Requiem's feature that makes some dropped items float on lava

Ah, I see. That's it then, I have EFR installed. However, I didn't tested it against yet. Thanks for the feedback!

**Comment by embeddedt** [comment]
This is fixed in the latest version.
