### ISSUE TITLE
The witch does not spawn in the swamp hut

### ISSUE THREAD

**Issue by Alex-1248** [embeddedt/ArchaicFix#115]
It appears that AF prevents the witch from spawning in the swamp hut under certain conditions.

Seed:
8818163494582849514

Hut coordinates:
x: 291, y: 72, z: 276

If AF is installed, then when I create a world with this seed, I never find the witch in this hut. If I create a world without AF, then I always find a witch in this hut. 

I also tried another seed (7892649471625196211) where the hut was located near the player's spawn point and in this case the witch almost always spawned in the hut regardless of the presence of AF. The only difference between these seeds that I see besides the distance from the player's spawn point is that in the first case there is a cave, several tunnels, and lava under the hut, while in the second case there is only one cave with a pond under the hut.

**Comment by Alex-1248** [comment]
The problem is somehow related to the fixMobSpawnsAtLowRenderDist option. If this option is turned off, then when I create a world with the first seed, I always find a witch in this hut.

**Comment by embeddedt** [comment]
This sounds like it's just https://bugs.mojang.com/browse/MC-108664 (which does affect versions before 1.10, the old issues were closed as duplicates for some reason). The reason it happens with `fixMobSpawnsAtLowRenderDist` but not with vanilla is likely the fact that this option lowers the despawn range of mobs if your render distance is small enough (this is to keep enough mobs spawned around the player). That means the witch has a higher chance of despawning before you get to the hut.

Fixing MC-108664 should be enough to fix this problem and seems like the intended game mechanic, anyways.

**Comment by embeddedt** [comment]
Does https://github.com/embeddedt/ArchaicFix/actions/runs/8033061660 fix the issue?

**Comment by Alex-1248** [comment]
Yes, the problem is fixed. The witch now appears in the hut with fixMobSpawnsAtLowRenderDist enabled.

**Comment by embeddedt** [comment]
:+1: Fix released in 0.7.2.
