### ISSUE TITLE
Various GT6 mixins cause errors when other GT is found (for example the custom GT5u in GTNH)

### ISSUE THREAD

**Issue by chochem** [embeddedt/ArchaicFix#116]
Various GT6 mixins cause errors when other GT is found instead (for example in the custom gt5u in GTNH)
[archaicfixerrors.txt](https://github.com/embeddedt/ArchaicFix/files/14540694/archaicfixerrors.txt)
(using archaicfix-0.7.1 in GTNH-nightly353)

I assume there is only a check for 'gregtech' being present which is rather unspecific. If detection of gt6 specifically is not easy to do, a config to turn off gt6 mixins (one-by-one or all) would also work as a solution.

**Comment by SilearFlare** [comment]
Shoe's on the other foot innit
now you see the world through our :eyes: 

GT6 detection is actually very simple, it's only a matter of specifying 
`Loader.isLoaded('gregtech') && !Loader.isLoaded("gregapi")`

**Comment by makamys** [comment]
The code you're describing detects GT5u, not GT6.

For clarity's sake, here are the modids declared by each major GT version:
- [GregTech 4 (Nukepowered port)](https://github.com/Nukepowered/GregTech4): `gregtech_addon`
- [GregTech 5U (GTNH fork)](https://github.com/GTNewHorizons/GT5-Unofficial): `gregtech`
- [GregTech 6](https://gregtech.mechaenetia.com/downloads/gregtech_1.7.10/index.html): `gregtech`, `gregapi_post`, `gregapi`

Therefore for detecting GregTech 6 exclusively, a check for `gregapi` or `gregapi_post` would be appropriate.

(In fact, ArchaicFix already checks for `gregapi` [in one place](https://github.com/embeddedt/ArchaicFix/blob/6eaca760d2185b1cd158c4b753844f01885976cd/src/main/java/org/embeddedt/archaicfix/mixins/common/thermal/MixinTECraftingHandler.java#L15).)

**Comment by SilearFlare** [comment]
Well, good thing I never wrote that commit for gt6 checks on magic bees then, 'cause that's what I was gonna implement :smile: :+1:

**Comment by embeddedt** [comment]
Should be fixed
