### ISSUE TITLE
[1.7.10] archaicfix crash when start the game with optifine

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#12]
Seem to be incompatibility with multithreaded chunk loading

Mods list :
archaicfix-mc1.7.10-0.3.0
falsepatternlib-mc1.7.10-0.10.5
OptiFine_1.7.10_HD_U_E7
SpongeMixins-1.5.0(from gtnh)

Logs :
https://paste.ee/p/Jp2Qi

**Comment by embeddedt** [comment]
Multithreaded chunkloading is not intended to be compatible with OptiFine. It depends on the occlusion tweak which itself is not compatible.

**Comment by quentin452** [comment]
ok thx

**Comment by Abalieno** [comment]
Sorry to hijack, but now there are a number of different optimization mods and I'm wondering what's going to be the better alternative.

In this case Neodymium seems to cover the same area, and it says it works better with both Fastcraft and Optifine. So I assume that option overrides whatever is implemented Arachaicfix.

Or maybe you plan to find better solutions to Neodymium/Optifine?

**Comment by embeddedt** [comment]
Most of the modern optimization mods are compatible with one another. Neodymium implements additional optimizations that ArchaicFix does not and there is no reason not to use both.

ArchaicFix is compatible with FastCraft and OptiFine. The specific optimizations that are not compatible are intended to eventually be better than what FC/OF provided, rendering them unnecessary.

**Comment by makamys** [comment]
Yep, Neodymium complements ArchaicFix. It's only FastCraft and OptiFine that have major overlaps and incompatibilities with other optimization mods (and even each other), due to their closed source nature.

**Comment by embeddedt** [comment]
>  Neodymium does the chunk loading and Archaicfix corresponding feature is disabled

No, Neodymium and ArchaicFix optimize different parts of the renderer. No features are disabled when they're installed together.

The only mods that trigger disabling of major features are FastCraft and OptiFine because of how invasive they are.
