### ISSUE TITLE
[incompatibility] Ultramine core

### ISSUE THREAD

**Issue by abitaredomdepo** [embeddedt/ArchaicFix#122]
Crash at startup without any other mods.

ultramine: https://github.com/TheByKotik/ultramine_core
archaicfix-0.7.2
unimixins-all-1.7.10-0.1.17
[2024-07-07-7.log](https://github.com/user-attachments/files/16118228/2024-07-07-7.log)

**Comment by embeddedt** [comment]
UltraMine appears to be a hybrid server, like Crucible/Thermos. These are not supported.
