### ISSUE TITLE
[Incompatiblitity] CarbonConfig (and there for ChunkPregen)

### ISSUE THREAD

**Issue by Speiger** [embeddedt/ArchaicFix#123]
o/
Its really nice that you guys are using Primitive Collections.
But your stripped down version is now basically conflicting with carbon configs stripped down version ^^"

This really sucks because chunkpregen requires now carbon config...

With JarInJar i would just say, make your stripped version just a bit lower verisoned than mine and it might just work.
But this isn't working here.

Hmmmm....

**Comment by embeddedt** [comment]
Fixed in 0.7.4
