### ISSUE TITLE
[1.7.10] Crash when placing OpenBlocks XP tank (threaded chunk update incompatibility)

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#13]
edit : i found what settings crash with xp tank : 

disableBlockingChunkUpdates

logs : 

https://paste.ee/p/m1ahY

Config of archaicfix : 

https://mega.nz/file/f5UATA7A#t8iYgO7FUGVRSDZqzeW7G48zvruhTsP_jsPUv-1PV3w

Mods list : 

archaicfix-mc1.7.10-0.3.0
CodeChickenCore-1.7.10-1.0.7.48-universal
falsepatternlib-mc1.7.10-0.10.5
OpenBlocks-1.7.10-1.6.9-GTNH
OpenModsLibs-1.7.10-0.10.6
SpongeMixins-1.5.0

Step to reproduce : 

1 : make a world 
2 : place xp tank
3 : crash

**Comment by embeddedt** [comment]
I recommend you temporarily disable `enableThreadedChunkUpdates` until we get around to figuring out the cause of these crashes. `disableBlockingChunkUpdates` will work around the issue for player-placed blocks but not anything placed by a machine further away.

**Comment by quentin452** [comment]
ok
