### ISSUE TITLE
 [1.7.10] Lazy chunk loading outputs warnings in the log

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#14]
```
Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: -13
 z: -13
 loader: null
 world: Copie de Copie de Copie de Copie
 dimension: 0
 provider: net.minecraft.world.WorldProviderSurface
}
[01:30:54] [Server thread/INFO] [FML]: This should not happen. Please report this error to Forge.
```

these errors do not appear if archaic fix is disabled

archaic fix config : 

https://mega.nz/file/v08xzb7T#n8EW52qjt7ojtq7tVLE0BLw9Cj0xBrtAw4IEOvzpGpw

logs :

https://paste.ee/p/1oabK

Mods list :

archaicfix-mc1.7.10-0.3.0-6-gcf3e0ef
CoFHCore-[1.7.10]3.1.4-329
endercore-1.7.10-0.2.10
EnderIO-1.7.10-2.3.1.43
falsepatternlib-mc1.7.10-0.10.7
FpsReducer-mc1.7.10-1.10.3
SimplyJetpacks-MC1.7.10-1.5.3
SpongeMixins-1.5.0
ThermalExpansion-[1.7.10]4.1.5-248
ThermalFoundation-[1.7.10]1.2.6-118
triangulator-mc1.7.10-1.7.7

**Comment by embeddedt** [comment]
Disabling `lazyChunkLoading` should fix this.

**Comment by quentin452** [comment]
ok i will try

**Comment by quentin452** [comment]
yes its fixed

**Comment by embeddedt** [comment]
That option was quickly added to test higher render distances with the occlusion tweak without the integrated server stalling and crashing, so I'm not surprised it has issues in scenarios like these. I need to revisit its implementation at a later date.

**Comment by embeddedt** [comment]
Lazy chunk loading is completely removed in the next version.
