### ISSUE TITLE
[1.7.10] Mobs flicker on Xaero's Minimap

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#15]
this issue do not appear if archaic fix is disabled

Mods list :

archaicfix-mc1.7.10-0.3.0-6-gcf3e0ef
falsepatternlib-mc1.7.10-0.10.7
SpongeMixins-1.5.0
Xaeros_Minimap_21.10.27_Forge_1.7.10
XaerosWorldMap_1.14.1.20_Forge_1.7.10

Videos : 

Without archaic fix(.mkv)
https://mega.nz/file/mlM3USCB#RYJBvpm1bisQcGd6D4aQHSk2oEYdeCEBI4EwGqsLlF4

With archaic fix(.mkv)
https://mega.nz/file/30EAybpb#N726YnxXCDwzSDv7p1CE1pyWyXHdEgE6xost6dNQpMo

**Comment by quentin452** [comment]
i will try

**Comment by quentin452** [comment]
yes still occur

**Comment by quentin452** [comment]
its an issue with optimizeEntityTicking

**Comment by embeddedt** [comment]
Thanks, that helps a lot. I don't know exactly when I'll fix this but the symptoms sound fairly minor for now.

**Comment by embeddedt** [comment]
Fixed in 0.3.5.
