### ISSUE TITLE
[1.7.10] Water flashes to more opaque color

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#17]
This issue do not appear without archaicfix
This issue do not appear if enableOcclusionTweaks and enableThreadedChunkUpdates=false

I think this issue can make the game laggy

Mods list : 

archaicfix-mc1.7.10-0.3.0-6-gcf3e0ef
falsepatternlib-mc1.7.10-0.10.8
SpongeMixins-1.5.0

Video : 

https://mega.nz/file/bplUwBSK#oHYSewAJRen_678bSC9oyRp5Gyg_xsdHDyYvCoI1Jxk

Edit : other way to troobleshoot the bug using sand

https://mega.nz/file/ShVQmQII#MQIhV4OLxauCG8XZSs9HbkFzvV5OmXj-DSP5iAadxzw

Logs : 

https://paste.ee/p/cqLOI

Seed : 6124575442801218859
location : 943 68 907
(I found this to be a good place to take the test)

**Comment by makamys** [comment]
Pretty sure this is caused by `enableThreadedChunkUpdates`, I noticed it too while testing.
