### ISSUE TITLE
Sometimes certain subchunks are invisible when occlusion tweaks are enabled

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#18]
ATTENTION,the cave sometimes are not there, so you have to recreate the world

This issue do not appear without archaicfix
This issue do not appear if enableOcclusionTweaks and enableThreadedChunkUpdates=false

Mods list :

archaicfix-mc1.7.10-0.3.0-6-gcf3e0ef
falsepatternlib-mc1.7.10-0.10.8
SpongeMixins-1.5.0

Seed : 6124575442801218859
location : 937 65 924

Screenshot : 

when I walk away from the cave
https://imgur.com/LGFll0t.png

when i get closer to the cave
https://imgur.com/Ueb2XLH.png

**Comment by embeddedt** [comment]
These are known limitations of the occlusion system; it's not 100% perfect. Usually you can fix it by moving some blocks around till the cave is always visible.

**Comment by quentin452** [comment]
ok

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
