### ISSUE TITLE
[1.7.10] Block overlay bug when i place block at Y=64

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#19]
This bug do not appear if edit: disableBlockingChunkUpdates =false

Video : 

https://mega.nz/file/XkFlmAKB#XOw86IjKHn-P1Mu6exWyarNc5_-GjSea2vvEQGt6cNc

**Comment by embeddedt** [comment]
If `disableBlockingChunkUpdates` is enabled, this type of issue is expected to happen. However, if it's disabled, that would be a bug.

**Comment by makamys** [comment]
It's a bug with the occlusion tweak, it happens when `enableThreadedChunkUpdates` is set to false too.
