### ISSUE TITLE
[1.7.10] optimizeEntityTickingIgnoreList Not Working

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#20]
Build : archaicfix-mc1.7.10-0.3.0-13-gc6e3fc6

I tried 
    ```
  S:optimizeEntityTickingIgnoreList <
        ["WitherBoss", "EnderDragon"]
     >
    ```
and
    ```
  S:optimizeEntityTickingIgnoreList <
        "WitherBoss", "EnderDragon"
     >
     ```
But the WitherBoss and EnderDragon are still affected by optimizeEntityTicking

**Comment by makamys** [comment]
That's not the correct syntax for string lists in Forge config. The elements should be on separate lines without commas or quotation marks, like this:
```
    S:optimizeEntityTickingIgnoreList <
        WitherBoss
        EnderDragon
     >
```

By the way, in the default config "Wither" is used instead of "WitherBoss", I wonder if this is a bug.

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
No i don't think is a bug ,
