### ISSUE TITLE
[1.7.10] No cubes mod bug with archaic fix

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#26]
No cubes mod : https://www.gamemodd.com/minecraft/mods/4673-no-cubes-1710-172.html

Screenshot : 

With archaic fix

![Capture d’écran_2022-09-06_08-29-00](https://user-images.githubusercontent.com/42176772/188764189-d2ff740c-b182-4847-8e10-1486dd0adea4.png)

Without archaic fix

![Capture d’écran_2022-09-06_08-29-00](https://user-images.githubusercontent.com/42176772/188764227-d596c048-751c-488b-880e-b3478c642916.png)

**Comment by embeddedt** [comment]
Interesting. :laughing: However, I think I will steer clear of officially supporting these kinds of mods. I suspect this will be fixed if you turn off the occlusion tweak and/or threaded chunk updates; not sure though.
