### ISSUE TITLE
[1.7.10] Dragonapi bug with archaic fix

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#27]
Screenshot : 

with archaic fix 

![Capture d’écran_2022-09-07_09-32-14](https://user-images.githubusercontent.com/42176772/188817204-3c0de773-b581-437f-ba5e-7a2a116d28ee.png)

without archaic fix

![Capture d’écran_2022-09-07_09-33-27](https://user-images.githubusercontent.com/42176772/188817195-2fbe6979-d8a9-4187-8d3d-5af102f5754f.png)

**Comment by embeddedt** [comment]
Does it eventually load (even if it takes much longer) in the first case, and is there anything of note in the log when it happens?

**Comment by quentin452** [comment]
ok i will retry and wait

**Comment by quentin452** [comment]
i can watch some ores and enemies

**Comment by quentin452** [comment]
and the world never load

**Comment by quentin452** [comment]
its an issue with enableThreadedChunkUpdates

**Comment by embeddedt** [comment]
This might not be fixable since DragonAPI is closed-source and I recall False needing to do some special magic to patch it.

**Comment by quentin452** [comment]
ok

**Comment by Abalieno** [comment]
...Are you sure?

**Comment by quentin452** [comment]
@embeddedt

**Comment by embeddedt** [comment]
@Abalieno Yes. Visible source is not the same thing as open source, the approach DragonAPI uses to patch is pretty invasive, and the author is often... hostile towards other mod authors when it comes to compatibility.

**Comment by embeddedt** [comment]
After thinking about this some more I have decided that I will not pursue a patch for DragonAPI as it's too invasive. Disabling threaded chunk updates will be the official workaround. If we ever enable this by default in the future, I will add a feature that turns it off automatically if DragonAPI is detected.

**Comment by quentin452** [comment]
it seem thats issue is fixed now
