### ISSUE TITLE
Incorrectly named mod file causes crash

### ISSUE THREAD

**Issue by Serega007RU** [embeddedt/ArchaicFix#29]
Hello, I can't start minecraft with your mod, it gives such an error (see the end of the log)
What could be the problem?
[latest.log](https://github.com/embeddedt/ArchaicFix/files/9531228/latest.log)

**Comment by makamys** [comment]
What happens if you remove CoreTweaks?

**Comment by quentin452** [comment]
modslist?

**Comment by Serega007RU** [comment]
> What happens if you remove CoreTweaks?

Removing CoreTweaks did not help, the same error

**Comment by quentin452** [comment]
try update falsepatternlib
and crashguard is not needed i think , because coretweak have a crash to main menu

**Comment by quentin452** [comment]
and grimoire is not conpatible with archaicfix , use spongemixin or MixinBooter Legacy

**Comment by Serega007RU** [comment]
I did as you all said, it didn't help, here's a crash report with a new list of mods
[crash-2022-09-09_16.49.53-client.txt](https://github.com/embeddedt/ArchaicFix/files/9536024/crash-2022-09-09_16.49.53-client.txt)

**Comment by Serega007RU** [comment]
[mods.txt](https://github.com/embeddedt/ArchaicFix/files/9536191/mods.txt)

**Comment by quentin452** [comment]
maybe its an issue with the server , i see in your crash report thermos , kcauldron

**Comment by embeddedt** [comment]
The issue appears to be that your CoFH Core JAR is not named as expected, so ArchaicFix doesn't know to disable the patch which causes this crash.

Unfortunately I don't have a better solution with the tools currently available for 1.7 than asking you to rename your JAR to not have a space in it (so it starts with `CoFHCore`, case doesn't matter).

https://github.com/embeddedt/ArchaicFix/blob/99070353b2c2cd211d3fab0324b9d378c0652a46/src/main/java/org/embeddedt/archaicfix/asm/TargetedMod.java#L27

**Comment by Serega007RU** [comment]
Yes, renaming `CoPH Core.jar` to `CoFHCore.jar` (without a space) solved this problem. It is very strange to rely only on the name of the jar file because the user can rename the mod any way

**Comment by embeddedt** [comment]
I agree, and in 1.12 we don't need to rely on the JAR name like this, but for some reason it seems to be the standard approach in 1.7 at the moment.

**Comment by embeddedt** [comment]
This issue will be fixed in the upcoming 0.5.0 version.

**Comment by embeddedt** [comment]
Fixed (finally) in 0.5.0! :tada:

**Comment by Serega007RU** [comment]
Thank you for your work! Any other mod author would say just rename the mod and that's it, and you dealt with the problem thoroughly and eliminated it at the root. Thank you for responsibly treating such a non-critical problem
