### ISSUE TITLE
Commit 2c60956 breaks fastcraft compatibility [crash at startup]

### ISSUE THREAD

**Issue by tyrael93** [embeddedt/ArchaicFix#3]
I updated my build to [the second-to-last lighting commit](https://github.com/embeddedt/ArchaicFix/commit/2c60956719cdc9e25177ebb80ff06350827c54da) for testing purposes and the game crashed, citing fastcraft's failed initialization. A copy of the crash can be found here https://paste.ee/p/JKi6A
I can confirm that the game runs fine [up to the previous sound system commit](https://github.com/embeddedt/ArchaicFix/commit/3b126ef44a631dfaceb4df5952f1ce0c933aa34b) with the same configs.

I understand that it's routine to crash with such bleeding edge, unreleased versions, but since it was the first time I had an issue with the mod at all, I wanted to file a report, just in case.
Thank you in advance for your patience and have a pleasant Sunday!

**Comment by embeddedt** [comment]
Thanks! Bleeding-edge reports are greatly appreciated.
