### ISSUE TITLE
Crash(

### ISSUE THREAD

**Issue by Arpupkin** [embeddedt/ArchaicFix#30]
[crash-2022-09-10_15.12.17-client.txt](https://github.com/embeddedt/ArchaicFix/files/9540317/crash-2022-09-10_15.12.17-client.txt)

**Comment by embeddedt** [comment]
Please send the full log.

**Comment by Arpupkin** [comment]
[lasted.txt](https://github.com/embeddedt/ArchaicFix/files/9540356/lasted.txt)

**Comment by embeddedt** [comment]
```
[15:09:07] [main/FATAL]: Mixin prepare failed preparing client.core.MixinFMLClientHandler in mixins.archaicfix.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.archaicfix.json:client.core.MixinFMLClientHandler target cpw.mods.fml.client.FMLClientHandler was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.archaicfix.json:client.core.MixinFMLClientHandler target cpw.mods.fml.client.FMLClientHandler was already transformed.
```

One of your other mods is loading a Forge class too early. You would need to bisect to figure out which mod that is. My guess would be Liteloader or a Liteloader mod, but I am not sure.

**Comment by makamys** [comment]
You might be able to fix this by adding [Mixingasm](https://github.com/makamys/Mixingasm).

**Comment by quentin452** [comment]
try add Gilded Game Utils - Fix and delete Gilded Game Utils

**Comment by embeddedt** [comment]
Closing as I don't think I can fix this on my end.
