### ISSUE TITLE
Incompatibility with Lumy Skin Patch

### ISSUE THREAD

**Issue by xJon** [embeddedt/ArchaicFix#31]
Report: https://mclo.gs/knhrylY
(Couldn't find a configuration option regarding `mixins.archaicfix.json:client.core.MixinSkinManager`, but I might be misunderstanding this crash report)
Thanks!

**Comment by embeddedt** [comment]
I can't reproduce this with LiteLoader, VoxelMap, and ArchaicFix installed.

**Comment by xJon** [comment]
I've found out it's actually just an incompatibility with [Lumy Skin Patch](https://www.curseforge.com/minecraft/mc-mods/lumy-skin-patch), I assume ArchaicFix does the same thing?

**Comment by embeddedt** [comment]
Hmm, I thought Lumy Skin Patch shouldn't be necessary on 1.7.10. ArchaicFix fixes a memory leak with skins that causes the client to hold on to old worlds even after you switch dimensions.

**Comment by xJon** [comment]
It's supposed to have various optimizations for skins on 1.7.10, e.g. Alex format, LAN support, Statue Mod

**Comment by xJon** [comment]
Do you think the incompatibility is due to ArchaicFix doing something Lumy Skin Patch is already doing? If so, would it be possible to have that be configurable on ArchaicFix's end so both mods could run together?

**Comment by embeddedt** [comment]
The memory leak patch is probably incompatible with something Lumy does. Unfortunately I don't have time anytime soon to figure out why it's incompatible, but yes, I can add a config option.

**Comment by xJon** [comment]
Thank you! Should I use the latest development version or should I wait for a new release?

**Comment by embeddedt** [comment]
You can safely use the development version. I doubt I'll change much, if anything between that and the next release.

**Comment by makamys** [comment]
I had a chat with Lumy, the issue happened because LSP replaces `SkinManager$2` with its own version compiled via MCP 9.08, which was missing the `field_152636_b` field.

We reimplemented the memory leak fix on LSP's side, and added a dummy `field_152636_b` field so mods that expect it to be there don't get confused.

```patch
--- a/minecraft/net/minecraft/client/resources/SkinManager.java
+++ b/minecraft/net/minecraft/client/resources/SkinManager.java
@@ -11,6 +11,7 @@ import com.mojang.authlib.minecraft.MinecraftSessionService;
 import com.mojang.authlib.minecraft.MinecraftProfileTexture.Type;
 import java.awt.image.BufferedImage;
 import java.io.File;
+import java.lang.reflect.Field;
 import java.util.HashMap;
 import java.util.Map;
 import java.util.concurrent.ExecutorService;
@@ -78,6 +79,9 @@ public class SkinManager
             final ImageBufferDownload var8 = p_152789_2_ == Type.SKIN ? new ImageBufferDownload() : null;
             ThreadDownloadImageData var9 = new ThreadDownloadImageData(var7, p_152789_1_.getUrl(), field_152793_a, new IImageBuffer()
             {
+                //fix to ensure compatibility with ArchaicFix --> https://github.com/embeddedt/ArchaicFix/issues/31
+                public SkinAvailableCallback field_152636_b = null;
+
                 private static final String __OBFID = "CL_00001828";
                 public BufferedImage parseUserSkin(BufferedImage p_78432_1_)
                 {
@@ -98,6 +102,22 @@ public class SkinManager
                     if (p_152789_3_ != null)
                     {
                         p_152789_3_.func_152121_a(p_152789_2_, var4);
+
+                        // Fix memory leak
+                        for (java.lang.reflect.Field f : getClass().getDeclaredFields()) {
+                            if (f.getType().equals(SkinManager.SkinAvailableCallback.class)) {
+                                f.setAccessible(true);
+                                try {
+                                    //System.out.println("Reset SkinAvailableCallback reference in field " + f.getName());
+                                    f.set(this, null);
+                                } catch (Exception e) {
+                                    System.out.println("Failed to reset SkinAvailableCallback reference in field " + f.getName());
+                                    e.printStackTrace();
+                                }
+                            } else {
+                                    //System.out.println("Not a SkinAvailableCallback reference in field " + f.getName());
+                            }
+                        }
                     }
                 }
             });
```

**Comment by xJon** [comment]
Thank you @makamys and Lumy for figuring this out, this is no longer an issue using the [latest 1.7.10 version](https://www.curseforge.com/minecraft/mc-mods/lumy-skin-patch/files/3990740) of Lumy Skin Patch :)
