### ISSUE TITLE
[1.7.10] Crash between evilnotchlib and archaicfix

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#33]
When disable archaicfix it does not crash

mods list : 

archaicfix-mc1.7.10-0.3.0-16-g059b8b4
confighelper-1.2.4.8
00gasstation-mc1.7.10-0.3.0
falsepatternlib-mc1.7.10-0.10.10

logs : 

https://paste.ee/p/UGYST

**Comment by makamys** [comment]
Try disabling `clearLaunchLoaderCache`. It looks like Evil Notch Lib implements as similar optimization to that one, causing a conflict.

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
thx
