### ISSUE TITLE
[1.7.10] Optimizeentityticking greatly reduce mob spawning

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#35]
tested in flat world on my modpack

Optimizeentityticking disabled
![Capture d’écran_2022-09-18_17-25-53](https://user-images.githubusercontent.com/42176772/190914971-f13fa52f-1cda-4736-a898-7bf35b68a57c.png)

Optimizeentityticking enabled
![Capture d’écran_2022-09-18_17-25-27](https://user-images.githubusercontent.com/42176772/190914973-57486df0-c88f-467f-8113-4f55d491fb2a.png)

**Comment by embeddedt** [comment]
Fixed in 0.3.5.
