### ISSUE TITLE
Crash between CoFH-Core and ArachicFix

### ISSUE THREAD

**Issue by DarkBum** [embeddedt/ArchaicFix#37]
I don't really know how this came to be, but after a lot of trying around, loading and not loading different mods and coremods, I managed to track down an issue that apparently makes the game crash even before loading [so no crash report, sorry :/] when I load ArchaicFix, GasStation [replacement for SpongeMixin and MixinASM] and FalsePatternLib together with a bunch of other mods that don't seem to be connected and CoFH-Core.

For now I've removed CoFH-Core, as I apprently didn't even need it for the modpack to function, but if you could look into it and notify me, that'd me really great :)

**Comment by embeddedt** [comment]
Probably the same issue as #29.

**Comment by DarkBum** [comment]
It was. Sorry ^^"
