### ISSUE TITLE
itemLagReduction is incompatible with Ships Mod

### ISSUE THREAD

**Issue by syndicate25** [embeddedt/ArchaicFix#38]
Using the latest 0.3.2 version, dropped items float to the ground so slowly, if I don't move out of their way, I pick them up again.

Problem does not occur without ArchaicFix installed.

I don't recall this as an issue in 0.3.0, but I can test that tomorrow if needed.

Here's a short video I took:
https://youtu.be/xYTh0cUA2U0

**Comment by quentin452** [comment]
mods list?

**Comment by syndicate25** [comment]
![Mod List](https://user-images.githubusercontent.com/22588398/191073166-9ab43da1-e9d7-447e-8265-ea1f5fffc196.png)

**Comment by quentin452** [comment]
give me the archaicfix cfg

**Comment by syndicate25** [comment]
Removed BugPatch.  No change, still slowly floating to the ground.

**Comment by syndicate25** [comment]
It's a conflict between ArchaicFix and Ships mod.

Is there anything you can check on your end to see if it can be resolved?  I know Ships is not getting any more updates, so any help would be appreciated.

**Comment by embeddedt** [comment]
I will see if I can make it work properly, if not I will add a config to disable the optimization which causes this.

**Comment by syndicate25** [comment]
So it appears it may be also causing an item dup glitch.  See latest video:

https://youtu.be/hv-YgFmymnc

**Comment by embeddedt** [comment]
Weird. All that's being done is to throttle how often the item moves when it is stationary (somehow this other mod must cause the item to seem stationary to my code), so I'm not sure why that would allow duplication.

**Comment by makamys** [comment]
Can you (syndicate) check if disabling `itemLagReduction` fixes anything? That should disable the aforementioned code.

**Comment by syndicate25** [comment]
> Weird. All that's being done is to [throttle](https://github.com/embeddedt/ArchaicFix/blob/01937440540c1a2f9906f53a25e0c1cdb51d27f3/src/main/java/org/embeddedt/archaicfix/mixins/common/core/MixinEntityItem.java) how often the item moves when it is stationary (somehow this other mod must cause the item to seem stationary to my code), so I'm not sure why that would allow duplication.

That actually would make sense since it allows you to make moving ships in the game, so it must have to convince MC that your stuff is not moving while on the ship.




> Can you (syndicate) check if disabling `itemLagReduction` fixes anything? That should disable the aforementioned code.

I'll give that a try and let you know if it is fixed.

**Comment by syndicate25** [comment]
Looks like that has solved the issue with the floating items.  I haven't been able to reproduce the item duping yet either since items are no longer falling slow enough to be caught mid-air.

Any chance of a fix on that section of the code to be able to use itemLagReduction in the future?

**Comment by embeddedt** [comment]
Possibly, but it will be a while, as I have very little time to devote to the mod right now.

**Comment by makamys** [comment]
Telomerase's Ships Mod fork just received a patch that makes the movement hook less intrusive (https://github.com/TeloDev/Cuchaz-Ships/pull/2). It might be worth checking if `itemLagReduction` is compatible with it now (this could be tested with ArchaicFix 0.3.2).
