### ISSUE TITLE
Crashes with EndlessIDs.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#4]
https://pastebin.com/mHGR9y0w
[latest.log](https://github.com/embeddedt/ArchaicFix/files/9079933/latest.log)

![image](https://user-images.githubusercontent.com/51277766/178163000-1721e9f7-f451-4ce4-814f-d98555522ae7.png)

**Comment by embeddedt** [comment]
This should be fixed with the latest commit; you'll need to wait a bit because GitHub takes a long time (10 minutes) to recompile the mod lately.
