### ISSUE TITLE
[1.7.10] Fps stuttering when I enter and leave water

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#44]
Archaicfix on
enableOcclusionTweaks=true
noticeable stuttering 400 fps less (2200 fps -> 1800 fps)

https://mega.nz/file/O8UXUISS#qcKeKeyQinpF3m43wTCqUbEGYeDdgn7PYIrZ1DHDq9M

Archaicfix on
enableOcclusionTweaks=false
less stuttering 100 fps less (1400 fps -> 1300 fps)

https://mega.nz/file/XtNi3AiQ#GiDJS840zYjUaZaiS07GeliffoGYUSUwWK7-qk41FOA

Archaicfix off
less stuttering 100 fps less (1900 fps -> 1800 fps)

https://mega.nz/file/Ho1GjACD#Tb_2hrilI3oMNLFWgdxgQ6hLwgrk1ELL3Xaq3x7peM4

**Comment by makamys** [comment]
Are you sure this is caused by entering water in particular? Doesn't the same thing happen if you fly up and down above water (between Y=70 and Y=75 for example)?

**Comment by quentin452** [comment]
you mean do I have the same problem between Y=70 and Y=75 without going into the water?

**Comment by makamys** [comment]
Yeah.

**Comment by quentin452** [comment]
no i don't have the issue

**Comment by quentin452** [comment]
I just have 100 - 200 fps difference

**Comment by quentin452** [comment]
the water in my test Y=62

**Comment by makamys** [comment]
What about when moving between Y=75 and Y=85? I'm thinking it could be about traversing a subchunk boundary (such as Y=64 and Y=80).

**Comment by quentin452** [comment]
i will try between 75 and 85

**Comment by quentin452** [comment]
no issue

**Comment by makamys** [comment]
Hm. I guess it really is about water then. I'm going to say this is low priority though, since you still get about the same amount of FPS (1800) with ArchaicFix in the worst case as without it.

**Comment by quentin452** [comment]
yes , i know 1800 fps is alot :D

**Comment by quentin452** [comment]
i tried when i go in the water, instead of looking ahead i look at the sky and there is stuttering

when i test between y level 75 and 85 i don't stutter

it really is a water problem

**Comment by makamys** [comment]
Actually I'm not sure if it's really caused by crossing the water's surface. I just tested and I get \~180 fps flying up and down above water (y=64\~67), \~170 fps if I'm crossing its surface (y=59\~63) and \~160 fps if I stay underwater (y=55\~59). This is when I'm looking forward. If I'm looking upwards, it's \~220, \~200, and \~190 fps respectively. So my fps drops *while* I'm underwater, not when I go underwater.

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
