### ISSUE TITLE
[1.7.10] Something (likely another mod) has attempted to modify the world's state from the wrong thread!

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#45]
descriptions : 
Make a new world , and you will get warns

mods lists : 

[1.7.10][SMP]DivineRPG-1.4.1.5
00gasstation-mc1.7.10-0.3.5
archaicfix-mc1.7.10-0.3.3
falsepatternlib-mc1.7.10-0.10.13

logs : 

[latest.log](https://github.com/embeddedt/ArchaicFix/files/9751360/latest.log)

Warns caused by DivineRPG

**Comment by embeddedt** [comment]
Fixed, will be included in the next release after 0.3.4.
