### ISSUE TITLE
LOTR causes a crash with this mod.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#49]
Since the LOTR mod isn't open-source, I can't really help much. Yell at their devs.

Tested with/without other mods, same issue.

https://pastebin.com/yRbJKcSk

**Comment by embeddedt** [comment]
The crash report you gave me indicates an issue with EndlessIDs, not ArchaicFix.

**Comment by MagmaBro123** [comment]
Ah. Huh, so I was right the first time. Already opened an issue there beforehand.

**Comment by embeddedt** [comment]
Closing since it's not on my end but let me know if ArchaicFix turns out to be part of the problem.

**Comment by MagmaBro123** [comment]
Me being an idiot apparently. Fixed via Discord.
