### ISSUE TITLE
Make the Mod Options GUI better, like in 1.12.2.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#53]
Title. Add filtering options, allow scrolling through the list via mouse, add a search, etc.

![2022-11-06_16 34 13](https://user-images.githubusercontent.com/51277766/200201669-c57ad15d-d5e5-4c99-b67e-0e9373b7b0d9.png)

Also, disable the 'Disable' button. Why Forge added this? I don't know lol.

**Comment by juraj-hrivnak** [comment]
Mentioned functionality is already implemented in EnderCore.

**Comment by embeddedt** [comment]
Closing as I don't have motivation to work on FML feature backports for the time being. Pull requests will be accepted if anyone feels like taking this up.
