### ISSUE TITLE
Backport 1.13x's biome blending slider/option.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#55]
Title. Allow biome blending to be controlled, so you don't have these harsh edges between biomes. Happens with/without other mods, and on Vanilla itself.

![2022-11-12_23 25 31](https://user-images.githubusercontent.com/51277766/201508923-c759c214-ea0a-46e0-a172-a6b9a86f5c90.png)

**Comment by embeddedt** [comment]
Not planned; PRs welcome.
