### ISSUE TITLE
Immediate crash upon launch

### ISSUE THREAD

**Issue by Zsashas** [embeddedt/ArchaicFix#56]
I have no idea what is causing this, something about spongepowered? Maybe MultiMC is the problem. It doesn't even make a crash report. Doesn't get far enough.

Log: https://gist.github.com/Zsashas/ead85258d240e088c48140d0a1431148

**Comment by makamys** [comment]
You're lacking one of ArchaicFix's dependencies, Mixin. You need to install one of SpongeMixins, MixinBooterLegacy, GasStation, or GTNHMixins. You also seem to be lacking FalsePatternLib, make sure you get that too.

**Comment by Zsashas** [comment]
Ah, missed the requirements. Makes sense.
