### ISSUE TITLE
Fix Ice's weird rendering.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#59]
Title.

This is a Vanilla issue, happens on 1.12 too I think.

![2022-12-04_17 24 59](https://user-images.githubusercontent.com/51277766/205525112-400b3000-7703-4407-906f-1fb9d86f56af.png)

**Comment by Omgise** [comment]
It would be great if it could be fixed :D

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
