### ISSUE TITLE
Add a copy to clipboard feature to Craft/MineTweaker.

### ISSUE THREAD

**Issue by MagmaBro123** [embeddedt/ArchaicFix#60]
Title.

In newer versions, CraftTweaker's '/mt (or ct) hand' command allows you to click on the item's name to copy it to your clipboard. This would make dealing with CraftTweaker scripts much easier, since long item names can be quite annoying to type repeatedly.

![2022-12-06_00 20 37](https://user-images.githubusercontent.com/51277766/205846943-489b7027-6d20-4fb6-ba75-74ee1de18c51.png)

**Comment by tyrael93** [comment]
Just copypaste it from your console log.

**Comment by tyrael93** [comment]
No, it stopped updating in 2016.
Technically there's a legacy update 3 from years back that uses the 1.12 version of zenscript which is slightly faster, but I've noticed that it breaks some 1.7 scripts.
The NH guys also maintain a fork of their own based on the legacy version.
https://github.com/GTNewHorizons/CraftTweaker

**Comment by MagmaBro123** [comment]
> No, it stopped updating in 2016. Technically there's a legacy update 3 from years back that uses the 1.12 version of zenscript which is slightly faster, but I've noticed that it breaks some 1.7 scripts. The NH guys also maintain a fork of their own based on the legacy version. https://github.com/GTNewHorizons/CraftTweaker

I'm talking about this.

![2022-12-07_11 23 40](https://user-images.githubusercontent.com/51277766/206264964-ab7ff67a-78e4-4f02-8e55-908d0cfae1eb.png)
![2022-12-07_11 23 54](https://user-images.githubusercontent.com/51277766/206264971-be5ea1c5-9211-4792-8a94-df499572ac1e.png)
