### ISSUE TITLE
[Sugesstion] Backport modern forge Mod loader has found a problem layout

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#66]
Description : Backport modern forge mod loader has found a problem to show multiple errors at once like in 1.12.2

Screenshot : 

1.7.10 error layout : 

https://i.imgur.com/yaQY7c6.png

1.12.2 error layout : 

https://i.imgur.com/rtOLRk3.png

**Comment by embeddedt** [comment]
Closing as I don't have motivation to work on FML feature backports for the time being. Pull requests will be accepted if anyone feels like taking this up.
