### ISSUE TITLE
MixinApplyError with Custom Skin Loader 14.6a

### ISSUE THREAD

**Issue by HowardZHY** [embeddedt/ArchaicFix#67]
[crash-2023-01-09_21.26.06-client.txt](https://github.com/embeddedt/ArchaicFix/files/10373507/crash-2023-01-09_21.26.06-client.txt)

**Comment by embeddedt** [comment]
This mod probably replaces some part of the vanilla skin manager, so you should disable `fixSkinMemoryLeak` in the ArchaicFix config.

**Comment by HowardZHY** [comment]
that works
