### ISSUE TITLE
Crash When i open F3 + watch the ground (Ambience)

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#68]
I don't crash when i disable Ambience

1 : Watch the ground
![image](https://user-images.githubusercontent.com/42176772/211395707-7d3aa07f-149d-45a2-8567-e9302b1ec9eb.png)

2 : Click on F3

3 : Get Crash

Crash report :

[crash-2023-01-09_21.17.22-client.txt](https://github.com/embeddedt/ArchaicFix/files/10376577/crash-2023-01-09_21.17.22-client.txt)

mods list : 

00gasstation-mc1.7.10-0.5.1
falsepatternlib-mc1.7.10-0.10.14
archaicfix-mc1.7.10-v0.4.0
Ambience 1.0-3 [here](https://www.curseforge.com/minecraft/mc-mods/ambience-music-mod)

**Comment by makamys** [comment]
I couldn't reproduce it but it should be fixed now in theory.

**Comment by quentin452** [comment]
fixed in archaicfix-mc1.7.10-v0.4.0-1-g00c17ab
