### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by LSK-LW** [embeddedt/ArchaicFix#71]
Error loading class: it/unimi/dsi/fastutil/longs/LongOpenHashSet (java.lang.ClassNotFoundException: The specified class 'it.unimi.dsi.fastutil.longs.LongOpenHashSet' was not found)

latest.txt : [https://pastebin.com/JVebT0TC](https://pastebin.com/JVebT0TC)

**Comment by embeddedt** [comment]
This issue occurs when FalsePatternLib does not download a library correctly. Please remove the `falsepattern` folder that is next to the mods folder and try relaunching the game.

**Comment by embeddedt** [comment]
This issue can no longer occur in 0.5.0 as Fastutil isn't downloaded at runtime anymore.
