### ISSUE TITLE
texture damage

### ISSUE THREAD

**Issue by iamsoNewBee** [embeddedt/ArchaicFix#74]
the normal
<img width="410" alt="image" src="https://user-images.githubusercontent.com/98573273/216092675-b64f2a6c-8fdf-4f8c-a90b-a14db4b57df9.png">
after
<img width="520" alt="image" src="https://user-images.githubusercontent.com/98573273/216093091-620fc637-9969-429d-85ad-2f84b0826888.png">
the block is the STONE LAVA CRUST form cavebioms mod.i dont know how to trigger it but have to do with this cfg
<img width="520" alt="image" src="https://user-images.githubusercontent.com/98573273/216093692-c4465fa1-31e3-429b-9974-96e6516e632f.png">

-----
_Addendum 1 - Originally posted by @iamsoNewBee in https://github.com/embeddedt/ArchaicFix/issues/91#issuecomment-1546704886_:

<img width="1280" alt="image" src="https://github.com/embeddedt/ArchaicFix/assets/98573273/4b6986ab-ce58-474a-9355-ea0f4fdd094a">
it`s the normal texture.but when  Occlusion Culling enabled, its lava part became transparent

**Comment by makamys** [comment]
Does this still happen with the latest development build?

**Comment by iamsoNewBee** [comment]
NO.

**Comment by makamys** [comment]
Managed to reproduce this with 0.5.0, and it only happened when threaded chunk updates were enabled. And indeed, it doesn't happen anymore.

8315eb5 was the commit that fixed it, so it had the same underlying cause as #52.
