### ISSUE TITLE
Crash with Extra Utilities

### ISSUE THREAD

**Issue by Starexify** [embeddedt/ArchaicFix#76]
I load ArchaicFix with Extra Utilities and it crashes.
Crash Log:

https://pastebin.com/jDtC3LW9

I delete Archaic Fix and it works.

**Comment by embeddedt** [comment]
Do you have a full log for when this crash occurs?

**Comment by Starexify** [comment]
> 

Sadly no, but now I get another crash when I try the same modpack with it, I'll make another issue for that better.
