### ISSUE TITLE
Crash with Chromaticraft 

### ISSUE THREAD

**Issue by Rimusp** [embeddedt/ArchaicFix#77]
Everytime i go to the Luminous Cliffs Biom for the first time the Game crashes if i load the world again it works about half the time.

Tested with: Archaic fix, Chromaticraft, DragonApi, Falsepatternlib, gasstation (ans natures compass but can confirm crash happens also without it)

crashlog: https://pastebin.com/W5SF4jae

**Comment by embeddedt** [comment]
I've asked Reika to implement a fix for this on their side.
