### ISSUE TITLE
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

### ISSUE THREAD

**Issue by MrSliTraP2716Lua** [embeddedt/ArchaicFix#82]
Trouble First
Crashed with CoFH Core/Lib java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker , but Fixed By UniMixins

Trouble Second
Crashed False Tweaks with UniMixins in additions file <span>#</span>2
+ UniMixins crashes with mods where Mixin is integrated, example Et FutuRum ReQuiem, but you need to be able to cut mixin, if there is no alternate distributive

PS: need to solve the first problem so that the second does not occur when using UniMixins

[crash-second.log](https://github.com/embeddedt/ArchaicFix/files/10967045/crash-second.log)
[startup_crash.log](https://github.com/embeddedt/ArchaicFix/files/10967047/startup_crash.log)
[optionsof.txt](https://github.com/embeddedt/ArchaicFix/files/10967048/optionsof.txt)
[falsetweaks.cfg.txt](https://github.com/embeddedt/ArchaicFix/files/10967061/falsetweaks.cfg.txt)
[ArchaicFix.cfg.txt](https://github.com/embeddedt/ArchaicFix/files/10967062/ArchaicFix.cfg.txt)

**Comment by makamys** [comment]
ArchaicFix requires a mixin loader such as UniMixins, so the first issue is not surprising if you're lacking one.

The Et Futurum issue is probably a user error. UniMixins can be safely used with mods that embed Mixin. The only way this would not be the case was if you renamed the jar.

I can't reproduce the FalseTweaks error. I get no crash with your config and the following mods:
```
archaicfix-0.5.0.jar
falsepatternlib-mc1.7.10-0.10.15.jar
falsetweaks-mc1.7.10-2.2.1.jar
OptiFine_1.7.10_HD_U_D6.jar
_unimixins-all-1.7.10-0.1.5.jar
```
