### ISSUE TITLE
lighting crash

### ISSUE THREAD

**Issue by mcmso** [embeddedt/ArchaicFix#85]
[crash-2023-03-28_19.49.26-server.txt](https://github.com/embeddedt/ArchaicFix/files/11089162/crash-2023-03-28_19.49.26-server.txt)

**Comment by embeddedt** [comment]
This is a known conflict with Reika's mods. I previously made Reika aware of the issue but there is nothing I can do until it is fixed on their end.

You could disable `enablePhosphor` in the config to hide the problem, but as noted that will reduce performance and possibly reintroduce lighting errors.
