### ISSUE TITLE
CRASH: java.lang.ClassCastException: net.minecraft.item.crafting.CraftingManager cannot be cast to org.embeddedt.archaicfix.recipe.IFasterCraftingManager

### ISSUE THREAD

**Issue by marlester-dev** [embeddedt/ArchaicFix#86]
my game crashes with this error:
[crash.txt](https://github.com/embeddedt/ArchaicFix/files/11089727/crash.txt)

**Comment by embeddedt** [comment]
Did you install UniMixins?

**Comment by embeddedt** [comment]
It should. The whole idea of UniMixins is to be backwards compatible with the other mixin mods like GasStation, since they often conflict with one another.
