### ISSUE TITLE
skipRenderingIfNotVisible Is laggy in my modpack, caused by entities?

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#89]
https://spark.lucko.me/k4qYhmLAdb
![Capture d’écran_2023-05-05_22-16-27](https://user-images.githubusercontent.com/42176772/236560578-cd5a9cd9-9e99-43e0-8244-f1a52cc3b7d0.png)

I get a significantly improvement when disabling this method in dev

edit : 

~480 fps with skipRenderingIfNotVisible  enabled with some special mobs through walls
~600 fps without skipRenderingIfNotVisible  enabled with some special mobs through walls

but it seem that disabling skipRenderingIfNotVisible make some issues

**Comment by couleurm** [comment]
hey, lurking around: what kinda "setting" even is skipRenderingIfNotVisible and how can it be modified? 

And what's spark.lucko.me, client side benchmarking?!! 🤨

**Comment by quentin452** [comment]
> hey, lurking around: what kinda "setting" even is skipRenderingIfNotVisible and how can it be modified?
> 
> And what's spark.lucko.me, client side benchmarking?!! raised_eyebrow

need to change the source code to remove skipRenderingIfNotVisible
And the i used /sparkc profiler run to profile client thread

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
