### ISSUE TITLE
Entities got deleted when go at lower value than Y=0 (tested in void world)

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ArchaicFix#90]
Mods lists :  

falsepatternlib-mc1.7.10-0.11.3
archaicfix-0.5.0
-unimixins-all-1.7.10-0.1.7.1

archaicfix config files

https://mega.nz/file/b90mETJC#kFFBxTv2M6awC-AckFnOfaFIyv5kUOnB6U5_RFomM_c ([mirror](https://github.com/embeddedt/ArchaicFix/files/11472405/archaicfix.cfg.txt))

logs  : 

[latest.log](https://github.com/embeddedt/ArchaicFix/files/11425125/latest.log)

screenshots : 

![2023-05-08_22 58 56](https://user-images.githubusercontent.com/42176772/236934187-5839bc74-46a3-4f92-b65c-1afd901c1807.png)
![2023-05-08_22 59 03](https://user-images.githubusercontent.com/42176772/236934194-0f1a12bf-dd0c-4ac3-83c6-9ce68e95e581.png)
![2023-05-08_22 59 22](https://user-images.githubusercontent.com/42176772/236934276-0c52f9ce-00eb-4ca5-86e5-f411f1271bfa.png)

**Comment by makamys** [comment]
The same thing happens in vanilla, hostile mobs generally despawn if you go over 128 blocks away from them.
