### ISSUE TITLE
water twitches when Occlusion Culling enabled.

### ISSUE THREAD

**Issue by iamsoNewBee** [embeddedt/ArchaicFix#91]
https://github.com/embeddedt/ArchaicFix/assets/13667520/bc87e54c-bde7-437e-a3b9-728caca92853

https://cowtransfer.com/s/9e8579a2024941
a video explained it

**Comment by iamsoNewBee** [comment]
<img width="1280" alt="image" src="https://github.com/embeddedt/ArchaicFix/assets/98573273/4b6986ab-ce58-474a-9355-ea0f4fdd094a">
it`s the normal texture.but when  Occlusion Culling enabled, its lava part became transparent

**Comment by makamys** [comment]
> a video explained it

This indeed looks like a duplicate of https://github.com/embeddedt/ArchaicFix/issues/17. Do you have `enableThreadedChunkUpdates` enabled, and are you using the latest development version of ArchaicFix? (You can grab it [here](https://nightly.link/embeddedt/ArchaicFix/workflows/gradle/main/Package.zip).)

> it`s the normal texture.but when Occlusion Culling enabled, its lava part became transparent 

This is unrelated, and a duplicate of https://github.com/embeddedt/ArchaicFix/issues/74.

**Comment by iamsoNewBee** [comment]
This indeed looks like a duplicate of #17. Do you have enableThreadedChunkUpdates enabled, and are you using the latest development version of ArchaicFix? (You can grab it here.)

YES.



and what the "unrelated" means?it return normal if i unenbaled Occlusion Culling

**Comment by iamsoNewBee** [comment]
BY THE WAY, if set     # EXPERIMENTAL: Replace the Thaumcraft hashing implementation. This really hasn't been tested and probably breaks everything. [default: false]
    B:betterThaumcraftHashing=true
U will found that ice is twitches

**Comment by makamys** [comment]
> YES.

In that case it's probably an incompatibility with something. Please post a mod list and your ArchaicFix config.

> and what the "unrelated" means?it return normal if i unenbaled Occlusion Culling of this mod

It's unrelated because this issue is about water twitching, the lava issue is a separate issue.

> BY THE WAY, if set

There is no way that's right, that setting doesn't affect rendering.

**Comment by iamsoNewBee** [comment]
do u still have the mod pack that i have send u before?u can try that and can the lava issue be fixed?

**Comment by makamys** [comment]
> do u still have the mod pack that i have send u before?

Yes. But I still want to see your current mod list and config.

**Comment by iamsoNewBee** [comment]
wait a moment.i have change the  acfix config to test.

**Comment by iamsoNewBee** [comment]
U will found that ice is twitching

it`s not crased by that.  my fault XD

**Comment by iamsoNewBee** [comment]
https://cowtransfer.com/s/aca6ef8a9d7b41
&nbsp;


东东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月14日(星期天) 凌晨0:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [embeddedt/ArchaicFix] water twitches when Occlusion Culling enabled. (Issue #91)





  
do u still have the mod pack that i have send u before?
  
Yes. But I still want to see your current mod list and config.

**Comment by makamys** [comment]
I only asked for a mod list and a config, not an entire modpack. 😅 (At least I assume that's what this is, it's taking a while to upload.)

On Windows you can generate one by opening the command prompt in your mods directory and running `dir > mods.txt`

**Comment by iamsoNewBee** [comment]
there are only mods and config there

**Comment by iamsoNewBee** [comment]
the stupdi web meet some problem ..wait.

**Comment by iamsoNewBee** [comment]
https://cowtransfer.com/s/d0e542f0e17840

**Comment by makamys** [comment]
Okay, it's like I suspected, you are *not* using the latest development build. Please try the version [I linked](https://nightly.link/embeddedt/ArchaicFix/workflows/gradle/main/Package.zip) (`archaicfix-0.5.0-23-gf645a92.jar`)

**Comment by iamsoNewBee** [comment]
let me have a try..

**Comment by iamsoNewBee** [comment]
well.. everything returns normal miraculously.cheers.XD

**Comment by iamsoNewBee** [comment]
so it`s a unreleased vision?
