### ISSUE TITLE
Fisk's Superheroes - enableOcclusionTweaks Crash

### ISSUE THREAD

**Issue by DarianLStephens** [embeddedt/ArchaicFix#93]
When trying to use certain abilities, namely intangibility, the game will immediately crash.
Oddly, the crash mentions key processing? That might just be where it starts, though.
https://pastebin.com/JNPd7GRw

**Comment by embeddedt** [comment]
Why is it always the ARR mods that do the weirdest things with Minecraft internals...

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
