### ISSUE TITLE
FalseTweaks - Item Voxellizer + enableThreadedChunkUpdates Strangeness

### ISSUE THREAD

**Issue by DarianLStephens** [embeddedt/ArchaicFix#94]
I'm genuinely not sure where to report this, so I'll do it here and make another issue on the FalseTweaks github pointing to it.
With both the ArchaicFix 'enableThreadedChunkUpdates' and the FalseTweaks 'VOXELIZER' options enabled, items keep doing this:
![2023-05-21_22 08 17](https://github.com/embeddedt/ArchaicFix/assets/15375876/869f56c6-d57f-4305-aeac-e5f5102e0af7)
![2023-05-21_22 08 20_3](https://github.com/embeddedt/ArchaicFix/assets/15375876/f1f6ecb9-7295-48ec-be0a-4d987ab3a48a)
![2023-05-21_22 08 21_2](https://github.com/embeddedt/ArchaicFix/assets/15375876/8e725366-933b-4ba9-a14b-5c71f9db074f)
Even in your hand:
![2023-05-21_22 07 53_2](https://github.com/embeddedt/ArchaicFix/assets/15375876/9e920c16-4665-4ff7-b636-32e8840c38f6)
![2023-05-21_22 07 53_3](https://github.com/embeddedt/ArchaicFix/assets/15375876/b41b1654-c0aa-465a-8935-f3f36deb406e)

**Comment by embeddedt** [comment]
It's probably FalseTweaks not being compatible with the fact that we use a tessellator on multiple threads.

**Comment by DarianLStephens** [comment]
I think I just encountered this unrelated to the FalseTweaks Voxellizer option.
When loading a save with loads of items on the ground, they popped around a bit, and a couple of them changed their icon to something else, but then stayed as normal once things settled down.

**Comment by embeddedt** [comment]
Threaded chunk updating & the occlusion tweak were removed from ArchaicFix in 0.7.0, so this issue is no longer relevant.
