### ISSUE TITLE
DragonAPI+ArchaicFix+ChromatiCraft

### ISSUE THREAD

**Issue by mcmso** [embeddedt/ArchaicFix#97]
https://paste.ubuntu.com/p/GMvsKVD9bc/
This problem can be repeated every time you encounter Lumafly
If you need any additional information, please contact me
I will reply as soon as possible

**Comment by embeddedt** [comment]
Needs to be fixed on Chromaticraft's end; I've just reported it.

**Comment by embeddedt** [comment]
I think this was fixed in a DAPI/CC update since July.
